services:
  api_service:
    build:
      context: .
      dockerfile: ./ml_conformer_generator/Dockerfile
    container_name: ml-conformer-generator
    environment:
      PORT: 8000
    expose:
      - 8000
    restart: "always"


