[build-system]
requires = ["setuptools >= 77.0.3", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "mlconfgen"
description = "Spatially-aware molecule generation via Equivariant Diffusion and GCN"
readme = "README.md"
dynamic = ["version"]
authors = [
    {name = "Denis Sapegin", email = "dasapegin@gmail.com"},
    {name = "Fedor Bakharev", email = "fbakharev@gmail.com"},
    {name = "Azamat Gafurov", email = "azamat.gafurov@gmail.com"},
]
maintainers = [
    {name = "Denis Sapegin", email = "dasapegin@gmail.com"},
    {name = "Azamat Gafurov", email = "azamat.gafurov@gmail.com"},
]
dependencies = [
    "rdkit>=2023.9.5",
    "numpy>=1.26.4",
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry",
]
license = "CC-BY-NC-ND-4.0 AND Apache-2.0"
license-files = ["LICENSE*"]
keywords = ["rdkit", "chemistry", "diffusion", "conformers"]

[project.optional-dependencies]
torch = [
    "torch>=2.2.1",
]

onnx = [
    "onnx>=1.20.1",
    "onnxruntime>=1.21.0",
    "onnxscript>=0.6.2"
]

full = [
    "torch>=2.0.1",
    "onnx>=1.20.1",
    "onnxruntime>=1.21.0",
    "onnxscript>=0.6.2",
]

[project.urls]
Homepage = "https://github.com/Membrizard/ml_conformer_generator"
Issues = "https://github.com/Membrizard/ml_conformer_generator/issues"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.setuptools_scm]
